version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html